[package]
name = "restsend-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.41", features = ["full", "fold"] }
quote = "1.0.8"
proc-macro2 = "1.0.70"
