[workspace]
resolver = "2"
members = ["crates/restsend-macros", "crates/restsend", "crates/restsend-wasm"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
#strip = true
